### ISSUE TITLE
Support for operator charms

### ISSUE THREAD

**Issue by AurelienLourot** [openstack-charmers/zosci-config#47]
With operator charms, zosci fails as follows:

```
2021-06-10 15:37:59.378335 | TASK [Run tox without tests]
2021-06-10 15:38:10.454339 | bionic-medium | MODULE FAILURE:
2021-06-10 15:38:10.455056 | bionic-medium | Traceback (most recent call last):
2021-06-10 15:38:10.455282 | bionic-medium |   File "<stdin>", line 102, in <module>
2021-06-10 15:38:10.455558 | bionic-medium |   File "<stdin>", line 94, in _ansiballz_main
2021-06-10 15:38:10.455744 | bionic-medium |   File "<stdin>", line 40, in invoke_module
2021-06-10 15:38:10.455898 | bionic-medium |   File "/usr/lib/python3.6/runpy.py", line 205, in run_module
2021-06-10 15:38:10.456046 | bionic-medium |     return _run_module_code(code, init_globals, run_name, mod_spec)
2021-06-10 15:38:10.456276 | bionic-medium |   File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
2021-06-10 15:38:10.456431 | bionic-medium |     mod_name, mod_spec, pkg_name, script_name)
2021-06-10 15:38:10.456582 | bionic-medium |   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
2021-06-10 15:38:10.456734 | bionic-medium |     exec(code, run_globals)
2021-06-10 15:38:10.456886 | bionic-medium |   File "/tmp/ansible_command_payload_a_amcarx/ansible_command_payload.zip/ansible/modules/command.py", line 675, in <module>
2021-06-10 15:38:10.457046 | bionic-medium |   File "/tmp/ansible_command_payload_a_amcarx/ansible_command_payload.zip/ansible/modules/command.py", line 620, in main
2021-06-10 15:38:10.457178 | bionic-medium | FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/src/review.opendev.org/openstack/charm-ceph-iscsi/build/builds/ceph-iscsi'
```

Indeed `charmcraft build` doesn't produce `build/builds/*` and doesn't seem to take an option to change the build output.

Failure visible here: https://review.opendev.org/c/openstack/charm-ceph-iscsi/+/784421

**Comment by ChrisMacNaughton** [comment]
This was resolved as can be seen in https://review.opendev.org/c/openstack/charm-ceph-iscsi/+/806947 :)
